# Generated by Django 5.1 on 2024-12-28 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان المستند')),
                ('document', models.FileField(upload_to='employee_documents/%Y/%m/%d/', verbose_name='الملف')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='myapp.employee', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'مستند الموظف',
                'verbose_name_plural': 'مستندات الموظفين',
            },
        ),
    ]
