# Generated by Django 5.1 on 2024-12-28 17:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_employeedocument'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['first_name', 'last_name'], 'verbose_name': 'موظف', 'verbose_name_plural': 'الموظفين'},
        ),
        migrations.RemoveField(
            model_name='employee',
            name='address',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='hire_date',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='salary',
        ),
        migrations.AddField(
            model_name='employee',
            name='educational_level',
            field=models.CharField(default='غير محدد', max_length=100, verbose_name='المستوى التعليمي'),
        ),
        migrations.AddField(
            model_name='employee',
            name='evaluation_month',
            field=models.CharField(default='غير محدد', max_length=50, verbose_name='شهر التقييم'),
        ),
        migrations.AddField(
            model_name='employee',
            name='job_class',
            field=models.CharField(default='غير محدد', max_length=100, verbose_name='الفئة'),
        ),
        migrations.AddField(
            model_name='employee',
            name='level',
            field=models.CharField(default='غير محدد', max_length=50, verbose_name='المستوى'),
        ),
        migrations.AddField(
            model_name='employee',
            name='next_promotion_date',
            field=models.DateField(blank=True, null=True, verbose_name='استحقاق الترقية'),
        ),
        migrations.AddField(
            model_name='employee',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات'),
        ),
        migrations.AddField(
            model_name='employee',
            name='organizational_unit',
            field=models.CharField(default='غير محدد', max_length=100, verbose_name='الوحدة التنظيمية'),
        ),
        migrations.AddField(
            model_name='employee',
            name='specialization',
            field=models.CharField(default='غير محدد', max_length=100, verbose_name='التخصص'),
        ),
        migrations.AddField(
            model_name='employee',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ بداية الخدمة'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='الاسم الأول'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='الاسم الأخير'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(default='غير محدد', max_length=100, verbose_name='الوظيفة'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('active', 'نشط'), ('inactive', 'غير نشط'), ('on_leave', 'في إجازة')], default='active', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
