# Generated by Django 5.1 on 2024-12-29 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_employee_options_remove_employee_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['name'], 'verbose_name': 'موظف', 'verbose_name_plural': 'الموظفين'},
        ),
        migrations.RemoveField(
            model_name='employee',
            name='email',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='next_promotion_date',
        ),
        migrations.AddField(
            model_name='employee',
            name='education_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الحصول على المؤهل'),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_number',
            field=models.CharField(default='0000', max_length=20, unique=True, verbose_name='رقم الموظف'),
        ),
        migrations.AddField(
            model_name='employee',
            name='evaluation_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ استحقاق التقييم السنوي'),
        ),
        migrations.AddField(
            model_name='employee',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='educational_level',
            field=models.CharField(default='', max_length=100, verbose_name='المستوى التعليمي'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='evaluation_month',
            field=models.CharField(default='', max_length=50, verbose_name='شهر التقييم'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='job_class',
            field=models.CharField(default='', max_length=100, verbose_name='الفئة'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='level',
            field=models.CharField(default='', max_length=50, verbose_name='المستوى'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='organizational_unit',
            field=models.CharField(default='', max_length=100, verbose_name='الوحدة التنظيمية'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(default='', max_length=100, verbose_name='الوظيفة'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='specialization',
            field=models.CharField(default='', max_length=100, verbose_name='التخصص'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ بداية الخدمة'),
        ),
    ]
