# Generated by Django 5.1 on 2024-12-29 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_employee_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='educational_level',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='المستوى التعليمي'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='evaluation_month',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='شهر التقييم'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='job_class',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='الفئة'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='level',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='المستوى'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='organizational_unit',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='الوحدة التنظيمية'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='الوظيفة'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='specialization',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='التخصص'),
        ),
    ]
