# Generated by Django 5.1 on 2024-12-29 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_employee_educational_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الملف')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف الملف')),
                ('file', models.FileField(upload_to='archives/%Y/%m/%d/', verbose_name='الملف')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('file_type', models.CharField(max_length=50, verbose_name='نوع الملف')),
                ('file_size', models.IntegerField(verbose_name='حجم الملف بالبايت')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archived_files', to='myapp.employee', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'ملف مؤرشف',
                'verbose_name_plural': 'الملفات المؤرشفة',
                'ordering': ['-upload_date'],
            },
        ),
    ]
